# Generated by Django 3.2.7 on 2022-08-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adSoyad', models.CharField(max_length=250, verbose_name='Ad Soyad')),
                ('eMail', models.EmailField(max_length=254, verbose_name='Email')),
                ('firmaAdi', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('adres', models.CharField(max_length=200, verbose_name='Adres')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesajınız')),
            ],
        ),
    ]
