# Generated by Django 3.2.7 on 2022-08-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenerator',
            name='engine',
            field=models.CharField(choices=[('Ricardo', 'Ricardo'), ('Dongfeng', 'Dongfeng'), ('Baudouin', 'Baudouin'), ('Deutz', 'Deutz'), ('Perkins', 'Perkins')], default='Ricardo', max_length=10, verbose_name='Motor'),
        ),
    ]
