# Generated by Django 3.2.7 on 2022-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_jenerator_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenerator',
            name='katalogEn',
            field=models.FileField(upload_to='dataEn/', verbose_name='DataSheet EN'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='katalogTr',
            field=models.FileField(upload_to='dataTr/', verbose_name='DataSheet TR'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='photo',
            field=models.FileField(upload_to='images/', verbose_name='Photo'),
        ),
    ]
