# Generated by Django 3.2.7 on 2022-08-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220818_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenerator',
            name='fiyat',
            field=models.CharField(max_length=15, null=True, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='frekans',
            field=models.CharField(max_length=10, null=True, verbose_name='Frekans'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='jenModel',
            field=models.CharField(max_length=10, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='katalogEn',
            field=models.FileField(null=True, upload_to='dataEn/', verbose_name='DataSheet EN'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='katalogTr',
            field=models.FileField(null=True, upload_to='dataTr/', verbose_name='DataSheet TR'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='kva',
            field=models.CharField(max_length=10, null=True, verbose_name='KVa'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='photo',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Photo'),
        ),
    ]
