# Generated by Django 3.2.7 on 2022-08-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220818_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenerator',
            name='katalogEn',
        ),
        migrations.RemoveField(
            model_name='jenerator',
            name='katalogTr',
        ),
        migrations.RemoveField(
            model_name='jenerator',
            name='photo',
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='engine',
            field=models.CharField(max_length=10, verbose_name='Motor'),
        ),
    ]
