# Generated by Django 3.2.7 on 2022-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220819_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenerator',
            name='catalogTr',
            field=models.FileField(null=True, upload_to='static/media', verbose_name='DataSheet TR'),
        ),
    ]
