# Generated by Django 3.2.7 on 2022-08-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_jenerator_catalogtr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jenerator',
            old_name='catalogTr',
            new_name='katalogTr',
        ),
        migrations.AddField(
            model_name='jenerator',
            name='katalogEn',
            field=models.FileField(null=True, upload_to='static/media', verbose_name='DataSheet EN'),
        ),
        migrations.AddField(
            model_name='jenerator',
            name='photo',
            field=models.FileField(null=True, upload_to='static/media', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='jenerator',
            name='engine',
            field=models.CharField(choices=[('Ricardo', 'Ricardo'), ('Dongfeng', 'Dongfeng'), ('Baudouin', 'Baudouin'), ('Deutz', 'Deutz'), ('Perkins', 'Perkins')], default='Ricardo', max_length=15, verbose_name='Motor'),
        ),
    ]
